name: Run Tests on Testing-Setup Branch

on:
  push:
    branches:
      - Testing-Setup # Run workflow only for the Testing-Setup branch

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      # Step 3: Install root dependencies (Testing)
      - name: Install dependencies
        run: npm install 
      
      # Step 4: Install dependencies for docs (Node.js server
      - name: Install Docs Dependencies
        run: |
          cd docs
          npm install
          cd ..

      # Step 5: Start Node Server to use docs folder
      - name: Start Node Server
        run: node ./docs/server.js &
        env:
          NODE_ENV: test

      # Step 6: Wait for the server to be ready
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000

      # Step 7: Run tests
      - name: Run tests
        run: npx cypress run
